
export const LOGIN_STATE = 'LOGIN_STATE' // 登陆状态
export const ACCOUNT_UID = 'ACCOUNT_UID' // 存取用户id
export const SET_LEVEL = 'SET_LEVEL' // 设置用户等级

export const SET_MUSIC_LIST = 'SET_MUSIC_LIST'
export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_DISC = 'SET_DISC'
export const SET_TOP_LIST = 'SET_TOP_LIST'
export const SET_PALY_PROGRESS='SET_PALY_PROGRESS'
export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'
export const SET_CURRENT_THUMB = 'SET_CURRENT_THUMB'

// export default {
//     SET_MUSIC_LIST: 'SET_MUSIC_LIST',
//     SET_PLAYING_STATE: 'SET_PLAYING_STATE',
//     SET_FULL_SCREEN: 'SET_FULL_SCREEN',
//     SET_PLAYLIST: 'SET_PLAYLIST',
//     SET_SEQUENCE_LIST: 'SET_SEQUENCE_LIST',
//     SET_PLAY_MODE: 'SET_PLAY_MODE',
//     SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
//     SET_DISC: 'SET_DISC',
//     SET_TOP_LIST: 'SET_TOP_LIST',
//     SET_PALY_PROGRESS: 'SET_PALY_PROGRESS',
//     SET_PLAY_HISTORY: 'SET_PLAY_HISTORY',
//     SET_CURRENT_THUMB: 'SET_CURRENT_THUMB'
// }



